Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define 'ansi' do |node|
      node.vm.hostname = 'ansi.local'
      config.vm.provision "ansible" do |ansible|
          ansible.playbook = "main.yml"
      end
  end    
end